# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/xladomaz/Desktop/projects/websocket_c

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/xladomaz/Desktop/projects/websocket_c

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/xladomaz/Desktop/projects/websocket_c/CMakeFiles /home/xladomaz/Desktop/projects/websocket_c/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/xladomaz/Desktop/projects/websocket_c/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

#=============================================================================
# Target rules for targets named websocket

# Build rule for target.
websocket: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 websocket
.PHONY : websocket

# fast build rule for target.
websocket/fast:
	$(MAKE) -f CMakeFiles/websocket.dir/build.make CMakeFiles/websocket.dir/build
.PHONY : websocket/fast

src/main.o: src/main.c.o

.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.c.s
.PHONY : src/main.c.s

src/websocket/generator.o: src/websocket/generator.c.o

.PHONY : src/websocket/generator.o

# target to build an object file
src/websocket/generator.c.o:
	$(MAKE) -f CMakeFiles/websocket.dir/build.make CMakeFiles/websocket.dir/src/websocket/generator.c.o
.PHONY : src/websocket/generator.c.o

src/websocket/generator.i: src/websocket/generator.c.i

.PHONY : src/websocket/generator.i

# target to preprocess a source file
src/websocket/generator.c.i:
	$(MAKE) -f CMakeFiles/websocket.dir/build.make CMakeFiles/websocket.dir/src/websocket/generator.c.i
.PHONY : src/websocket/generator.c.i

src/websocket/generator.s: src/websocket/generator.c.s

.PHONY : src/websocket/generator.s

# target to generate assembly for a file
src/websocket/generator.c.s:
	$(MAKE) -f CMakeFiles/websocket.dir/build.make CMakeFiles/websocket.dir/src/websocket/generator.c.s
.PHONY : src/websocket/generator.c.s

src/websocket/helper.o: src/websocket/helper.c.o

.PHONY : src/websocket/helper.o

# target to build an object file
src/websocket/helper.c.o:
	$(MAKE) -f CMakeFiles/websocket.dir/build.make CMakeFiles/websocket.dir/src/websocket/helper.c.o
.PHONY : src/websocket/helper.c.o

src/websocket/helper.i: src/websocket/helper.c.i

.PHONY : src/websocket/helper.i

# target to preprocess a source file
src/websocket/helper.c.i:
	$(MAKE) -f CMakeFiles/websocket.dir/build.make CMakeFiles/websocket.dir/src/websocket/helper.c.i
.PHONY : src/websocket/helper.c.i

src/websocket/helper.s: src/websocket/helper.c.s

.PHONY : src/websocket/helper.s

# target to generate assembly for a file
src/websocket/helper.c.s:
	$(MAKE) -f CMakeFiles/websocket.dir/build.make CMakeFiles/websocket.dir/src/websocket/helper.c.s
.PHONY : src/websocket/helper.c.s

src/websocket/websocket.o: src/websocket/websocket.c.o

.PHONY : src/websocket/websocket.o

# target to build an object file
src/websocket/websocket.c.o:
	$(MAKE) -f CMakeFiles/websocket.dir/build.make CMakeFiles/websocket.dir/src/websocket/websocket.c.o
.PHONY : src/websocket/websocket.c.o

src/websocket/websocket.i: src/websocket/websocket.c.i

.PHONY : src/websocket/websocket.i

# target to preprocess a source file
src/websocket/websocket.c.i:
	$(MAKE) -f CMakeFiles/websocket.dir/build.make CMakeFiles/websocket.dir/src/websocket/websocket.c.i
.PHONY : src/websocket/websocket.c.i

src/websocket/websocket.s: src/websocket/websocket.c.s

.PHONY : src/websocket/websocket.s

# target to generate assembly for a file
src/websocket/websocket.c.s:
	$(MAKE) -f CMakeFiles/websocket.dir/build.make CMakeFiles/websocket.dir/src/websocket/websocket.c.s
.PHONY : src/websocket/websocket.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... main"
	@echo "... websocket"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/websocket/generator.o"
	@echo "... src/websocket/generator.i"
	@echo "... src/websocket/generator.s"
	@echo "... src/websocket/helper.o"
	@echo "... src/websocket/helper.i"
	@echo "... src/websocket/helper.s"
	@echo "... src/websocket/websocket.o"
	@echo "... src/websocket/websocket.i"
	@echo "... src/websocket/websocket.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

